sonar.projectKey=devsecops-cicd-platform
sonar.projectName=DevSecOps CI/CD Platform
sonar.projectVersion=1.0

sonar.sources=frontend,backend
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/__pycache__/**,**/.venv/**,**/venv/**,**/.terraform/**

sonar.sourceEncoding=UTF-8