sonar.projectKey=devsecops-cicd-platform
sonar.projectName=DevSecOps CI/CD Platform
sonar.projectVersion=1.0

sonar.sources=frontend/src,backend/app
sonar.tests=frontend/tests,backend/tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/*.pyc,\
**/coverage/**,\
**/reports/**,\
**/.terraform/**,\
**/terraform.tfstate*,\
**/database/*.sql

sonar.javascript.node.maxspace=2048
sonar.python.version=3.12

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.scm.provider=git
