apiVersion: v1
kind: Secret
metadata:
  name: devsecops-secret
  namespace: devsecops
  labels:
    app.kubernetes.io/name: devsecops-secret
    app.kubernetes.io/part-of: devsecops-cicd-platform
type: Opaque

data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  SECRET_KEY: Y2hhbmdlLXRoaXMtZGV2ZWxvcG1lbnQtc2VjcmV0LWtleS1wbGVhc2UtcmVwbGFjZS1pbi1wcm9kdWN0aW9u