global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    project: devsecops-cicd-platform
    environment: development

rule_files:
  - /etc/prometheus/alert-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:

  # Prometheus monitors itself
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090